vim.keymap.set('i', '(', '()<left>', {noremap = true, silent = true})
vim.keymap.set('i', '[', '[]<left>', {noremap = true, silent = true})
vim.keymap.set('i', '{', '{}<left>', {noremap = true, silent = true})
vim.keymap.set('i', "'", "''<left>", {noremap = true, silent = true})
vim.keymap.set('i', '"', '""<left>', {noremap = true, silent = true})
